import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";
import Header from "./common/header";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ja' className='min-h-full'>
      <body className='light min-h-full'>
        <Header />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
